- name: deploy database and web server on node02
  hosts: node02
  become: yes
  gather_facts: no
  roles:
    - postgres
    - apache

- name: deploy application services on node01
  hosts: node01
  become: yes
  gather_facts: no
  roles:
    - application
  