#SPDX-License-Identifier: MIT-0
---
# tasks file for apache

- name: update and upgrade system 
  apt:
    update_cache: yes
    upgrade: yes

- name: install Apache
  apt:
    name: apache2
    state: present

- name: start Apache
  service:
    name: apache2
    state: started
    enabled: yes